### ISSUE TITLE
صندوق پیام روی اپ(اندروید) کاربر ها

### ISSUE THREAD

**Issue by Ario92** [chabok-io/chabok-starter-unity-old#1]
با سلام
راهی وجود داره که پیام هایی که کاربر دریافت کرده و یا قرار بوده دریافت کنه را روی دستگاهش ببیند. مثلا صندوق پیام. من فقط لینک زیر را دیدم اما برای پیاده سازیش مطلبی پیدا نکردم.

https://doc.chabok.io/mobile-usecases/introducing.html#%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%D8%A8%DA%A9%D9%86%D8%AF-%D8%A2%D9%86%DB%8C-realtime-backend-service

سپاس

**Comment by Ario92** [comment]
داخل داکیومنت بخش اندروید بخشی هست به نام پیام چابک که میشه تا  حدودی این کار را باهاش انجام داد اما درون پلاگین یونیتی این بخش موجود نیست.

ممنون میشم راهنمایی کنید. @Husseinhj

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام
<br>
دو راه برای راه اندازی صندوق پیام هست:
<br>
<ol>
<li>
پیام‌هایی که به کلاینت ارسال میشه رو دریافت کنید و داخل دیتابیس ذخیره کنید تا بتونید لیست پیام‌ها رو به کاربر نمایش بدید
</li>
<li>
برای دریافت لیست پیام‌ها <a href="https://apidoc.chabok.io/">api</a> وجود داره که لیست پیام‌های یک ماه اخیر رو برمیگردونه
</li>
</ol>
دریافت اعلان در داکیومنت یونیتی ذکر نشده ولی متد addNotificationHandler رو تست کنید ببینید در کتابخانه یونیتی موجود هست.
</div>
